name: Kitduels
version: '${project.version}'
main: prod.spooky.kitduels.Kitduels
api-version: '1.19'
description: Allows to Duel with other players With various Kits
commands:
  Duel:
    description: "Allows You to duel with another player"
    usage: /<command> <player> <kit> <map>
  Hub:
    description: "Teleports You to Server Hub"
    usage: /<command>
    aliases:
      - hub
  Accept:
    description: "Accept incoming duel requests"
    usage: /<command> <player>
  Decline:
    description: "Decline incoming duel requests"
    usage: /<command> <player>
  goto:
    description: "Go anywhere"